"""v2

Revision ID: 55712c1d5613
Revises: 8e2a84ba779c
Create Date: 2023-08-03 08:24:47.057216

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "55712c1d5613"
down_revision = "8e2a84ba779c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("middlename", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_holders", sa.Integer(), nullable=True),
        sa.Column("id_tickers", sa.Integer(), nullable=True),
        sa.Column("purchase_prise", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("selling_date", sa.Date(), nullable=False),
        sa.Column(
            "delta_day",
            sa.Integer(),
            sa.Computed(
                "selling_date - purchase_date",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["id_holders"],
            ["holders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_tickers"],
            ["tickers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchases")
    op.drop_table("holders")
    # ### end Alembic commands ###
