"""v3

Revision ID: 5a535756715e
Revises: 55712c1d5613
Create Date: 2023-08-03 08:52:45.769936

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5a535756715e"
down_revision = "55712c1d5613"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchases", sa.Column("purchase_price", sa.Float(), nullable=False))
    op.drop_column("purchases", "purchase_prise")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchases",
        sa.Column(
            "purchase_prise",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("purchases", "purchase_price")
    # ### end Alembic commands ###
