"""Holder change

Revision ID: 64998378c203
Revises: 5a535756715e
Create Date: 2023-08-05 02:24:32.911060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64998378c203"
down_revision = "5a535756715e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("holders", sa.Column("username", sa.String(), nullable=False))
    op.add_column("holders", sa.Column("password", sa.String(), nullable=False))
    op.add_column("holders", sa.Column("email", sa.String(), nullable=False))
    op.drop_column("holders", "firstname")
    op.drop_column("holders", "middlename")
    op.drop_column("holders", "surname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "holders", sa.Column("surname", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "holders",
        sa.Column("middlename", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "holders",
        sa.Column("firstname", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("holders", "email")
    op.drop_column("holders", "password")
    op.drop_column("holders", "username")
    # ### end Alembic commands ###
